/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Instructions
{
    public class InstructionsRequest : Message
    {
        public const string RosMessageName = "Instructions/Instructions";

        public string instructions { get; set; }

        public InstructionsRequest()
        {
            this.instructions = "";
        }

        public InstructionsRequest(string instructions)
        {
            this.instructions = instructions;
        }
    }
}
