/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.PickObject
{
    public class PickObjectRequest : Message
    {
        public const string RosMessageName = "PickObject/PickObject";

        public string target_object { get; set; }

        public PickObjectRequest()
        {
            this.target_object = "";
        }

        public PickObjectRequest(string target_object)
        {
            this.target_object = target_object;
        }
    }
}
